### ISSUE TITLE
Creating Real World Value for Open Source - 'Open' Educational Resources 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/open-innovation-curriculum#26]
Looking for ideas/perspectives!

Feed back is that students,  want real world value (that are not an experiment that might go away like badges), for example access to an organizational repo - a certificate. 

**As we develop a series of learning modules for Open Source Clubs, we are mindful that students have a lot to do, that it's easy to skim,  or not complete modules at all.** 

**Thus this question:**

 What real world value can we provide to technical students, interested in learning about open source on completion of a single learning module? Please add your thoughts in comments!  Thank you!

**Comment by dmarti** [comment]
How about some form of hosting for a project -- shell+web account, container hosting, or VPS depending on size and scope of project? If you complete your project we will provide a place to host it, live. Every time you return to do another event, you renew your hosting plan.

**Comment by jgmac1106** [comment]
@dmarti Yes, plus one to this. All the different clubs and orgs I have helped set up across the world always run into wanting their own domain and hosting.

We encourage github pages early on but thats not the same as "your own"

I think space and a domain registry for "certified open source clubs" with Mozilla branding would be a great incentive.

What do they get from completing one module? Noe sure. Google Maps has points for Local Guides like other gamified rewards.

LinkedIn endorsements seem to resonate with people. Maybe a menu of shout outs.

Maybe they get votes as to where to direct a small pool of donations. So if Mozilla has 4-5 target initiative X amount of money is divided by % of votes.

Maybe you have the right audiences but wrong gatekeepers. Target university instructors, campus club advisors, and/or bootcamps. They will take bits and pieces of modules and units and integrate these lessons into courses. 

Long term I think the movement will have better luck taking existing clubs open rather than trying to recruit people to start new clubs.

**Comment by hmitsch** [comment]
How about:
* access to software (e.g. SaaS offerings such as IRCcloud, ProductPlan, Community Analytics, etc.)

**Comment by hmitsch** [comment]
+1 on the LinkedIn incentive: invitation to a closed group, a badge/recommendation on your profile, etc
